Engine param
sepandhaghighi/pyrgg pull request #148
Opened 2023-08-06 08:52 UTC by sadrasabouri

#### Reference Issues/PRs
#145 
#### What does this implement/fix? Explain your changes.
This PR will add `engine` parameter to the PyRGG menu. Until now we only have one engine (Pyrgg engine) but new engines will be proposed using this architecture.

I tried to develop it as cohesive as I can. Using `engine` parameter from `result_dict` we can control further parameters needed for each generation method.

2023-08-08 07:26 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 

1. To make it possible to work with various engines dynamically, it is necessary to update both `get_input` and `_update_using_second_menu` functions.
2. I suggest renaming `MENU_ITEMS2` to a more appropriate name like `PYRGG_ENGINE_PARAMS`.
3. I agree with you regarding the bug in the order of `MENU_ITEMS1`. To resolve this issue, we need to convert it into the `MENU_ITEMS2` format.

2023-08-08 07:26 UTC, sepandhaghighi commented on CHANGELOG.md
> +- generation engine menu
Generation engine menu

2023-08-08 13:54 UTC, sadrasabouri commented
> 

1. Done (although I think we can use a class or at least an Enum for engines in future, too)
2. Done
3. That's a great approach. It's better to deal with in a separate PR.

2023-08-19 12:46 UTC, sepandhaghighi approved these changes
🚀

2023-08-19 12:47 UTC, merged