Extract `edge_gen`
sepandhaghighi/pyrgg pull request #157
Opened 2023-11-26 01:27 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
All graph generation methods share some common codes (similar use-cases of `edge_gen`. This PR solve this issue by:

+ Extracting `edge_gen`
+ Proposing a more general strategy for graph generation which is compatible with future generation engines

#### Any other comments?

2024-01-07 21:05 UTC, sepandhaghighi requested changes
@sadrasabouri Sorry for my late response 🥇 
Please take a look at my comments.

2024-01-07 21:05 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `dimacs_init` function removed
Move to `### Remove` (Take a look at previous sections)

2024-01-07 23:56 UTC, sadrasabouri commented
The newly introduced error has nothing to do with this PR and we should handle it in a separate PR.

2024-01-08 00:03 UTC, sepandhaghighi commented
> The newly introduced error has nothing to do with this PR and we should handle it in a separate PR.

It's not a big deal.
I will take care of it at the end of the review.🔥

2024-01-09 06:22 UTC, sepandhaghighi approved these changes
@sadrasabouri Well done 🚀

2024-01-09 06:22 UTC, merged