Erdos Reyni - G(n,m) engine added
sepandhaghighi/pyrgg pull request #177
Opened 2024-09-30 05:09 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
Erdős–Rényi G(n,m) random graph generation model support added

#### Any other comments?

2024-09-30 15:51 UTC, sepandhaghighi requested changes
@sadrasabouri Please review my comments 🔥

2024-09-30 15:51 UTC, sepandhaghighi commented on pyrgg/engines/erdos_reyni.py
> +    TOTAL_EDGE = (n * (n - 1)) // 2
My suggestion:

```
max_edge = (n * (n - 1)) // 2
```

2024-09-30 15:51 UTC, sepandhaghighi commented on pyrgg/engines/erdos_reyni.py
> +        m = min(m, 2 * TOTAL_EDGE)
My suggestion:

```
max_edge = 2 * max_edge
m = min(m, max_edge)
edge_mold = m * [1] + (max_edge - m) * [0]
...
```

2024-09-30 22:36 UTC, sadrasabouri commented
@sepandhaghighi would you please review this?

2024-10-01 13:02 UTC, sepandhaghighi approved these changes
🔥

2024-10-01 13:02 UTC, merged