New Engine: Stochastic Block Model (`sbm`)
sepandhaghighi/pyrgg pull request #189
Opened 2024-12-10 01:57 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
This PR added a new engine: [stochastic block model](https://en.wikipedia.org/wiki/Stochastic_block_model).
This generation model partitions `n` vertices into `k` set: $\{C_1, C_2, \cdots, C_k\}$, then a matrix $P_{k \times k}$ would assign the probability of existence of an edge between $v_i$ and $v_j$ with probability $P_{ij}$.

Also some minor edits for prior engines have been applied.

#### Any other comments?
Two points that need to be clarified:
1. Due to the technical debt from the prior inputting system implementation I couldn't add validation for `block_sizes` and `probability_matrix`. Let me know what we should do.
2. I implemented `self-loop` for this engine but we should note that the probability of self-loop is $P_{ii}$ for $v_i$ as well. If you think that's not appropriate we can remove it.

2024-12-10 23:03 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 
I believe that obtaining `probability_matrix` and `block_sizes` directly via the CLI is not advisable due to size issue! Instead, we can prompt the user for parameters such as `intra_probability`, `inter_probability`, and `number_of_blocks`. Based on these inputs, we can generate the `probability_matrix` and `block_sizes`, restricting custom edits to the **config** mode.

2024-12-14 22:45 UTC, sadrasabouri commented
Hey @sepandhaghighi, I applied the changes. This PR needed an immediate post-merge PR which takes into consideration the  following points:

- Add new tests for warnings to increase the coverage
- Modify save/load config to make it more engine-specific. We should only save engine-related information in the config file, maybe change the extension to represent the engine, and check for the formatting. An example of a config file now generated for SBM model is presented bellow.

```json
{
  "file_name": "asd",
  "number_of_files": 1,
  "vertices": 10,
  "max_weight": 1,
  "min_weight": 1,
  "min_edge": 0,
  "max_edge": 0,
  "edge_number": 0,
  "sign": true,
  "output_format": "JSON",
  "weight": true,
  "engine": "sbm",
  "direct": false,
  "self_loop": false,
  "multigraph": false,
  "config": true,
  "probability": 0.5,
  "blocks": 3,
  "inter_probability": 0.1,
  "intra_probability": 0.8,
  "block_sizes": [
    3,
    3,
    4
  ],
  "probability_matrix": [
    [
      0.9,
      0,
      0
    ],
    [
      0,
      0.9,
      0
    ],
    [
      0,
      0,
      0.9
    ]
  ],
  "pyrgg_version": "1.6"
}
```

2024-12-16 22:52 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 
I believe we can eliminate `self_loop` and `direct` from the inputs. These parameters can both be managed through the `probability_matrix`.

2024-12-16 22:52 UTC, sepandhaghighi commented on pyrgg/params.py
> +PYRGG_UNDIVISIBLE_WARNING_MESSAGE = "Warning : Vertices are not divisible by blocks. The last block will have the remaining vertices."
`[Warning] Vertices ...`

2024-12-16 22:52 UTC, sepandhaghighi commented on pyrgg/params.py
> +PYRGG_SBM_WARNING_MESSAGE = "[Warning] - In CLI mode, Stochastic Block Model gets the number of blocks and inter/intra probabilities. To get more detailed configuration, please save and edit the conf
1. Remove `In CLI mode,`
2. `[Warning] Stochastic ...`

2024-12-17 00:52 UTC, sadrasabouri commented
> @sadrasabouri Thanks for your efforts 💯 I believe we can eliminate `self_loop` and `direct` from the inputs. These parameters can both be managed through the `probability_matrix`.

I agree with removing `direct,` but that's not the case for the `self_loop`. `probability_matrix` identifies the probability of blocks, not nodes.

2025-05-07 21:38 UTC, sepandhaghighi approved these changes
🔥

2025-05-07 21:39 UTC, merged