Local CI via tox
sepandhaghighi/pyrgg pull request #62
Opened 2020-08-31 16:40 UTC by ivanovmg

#### Reference Issues/PRs
NA

#### What does this implement/fix? Explain your changes.

To check locally that tests and code linting are fine, one can use ``tox``.
This allows one to catch bugs related to incompatibilities with the earlier python versions, for example.

Install:
```
pip install tox
```

Run:
```
tox
```

I added py35, py36, py38, py38 and flake8 environments.

#### Any other comments?

2020-08-31 20:59 UTC, sepandhaghighi requested changes

2020-08-31 20:59 UTC, sepandhaghighi commented on dev-requirements.txt
> +flake8
Please add a version range for **flake8**, for example :
`flake8>=3.7.5`

2020-09-02 09:13 UTC, sepandhaghighi commented on dev-requirements.txt
> +flake8
after this edit, I will merge this PR ;-)

2020-09-03 10:12 UTC, sepandhaghighi approved these changes

2020-09-03 10:13 UTC, sepandhaghighi commented
@sadrasabouri Please review this PR, if everything is okay merge it after approval ;-)

2020-09-03 17:32 UTC, sadrasabouri approved these changes

2020-09-03 17:32 UTC, merged